### ISSUE TITLE
Save current state of Sonos before running Plugin

### ISSUE THREAD

**Issue by Stephan-b1** [Julius-Bendt/homebridge-sonos-player#1]
Hi there!
Don't know if this is an issue or a feature request.
If Sonos plays already music via Spotifiy, or plays TV sound via AMP the Plugin interrupts the current song and plays the configured MP3 file (until here, everything is as expected). But, Sonos stops playing anything after the MP3 file has been running.

Would it be possible to revert back to the audio that has been played before the plugin has been executed?

Cheers,
Stephan

**Comment by Julius-Bendt** [comment]
Hello Stephan,

thanks for your interrest in the plugin! 

I'll definitely look into it. I dont really have time this week though. I'll update the issue when I know more

**Comment by Julius-Bendt** [comment]
Hi @Stephan-b1,

I've added an option to play as a notification, which should fix your problem. 
I havent tested the code yet, or published it to npm yet. Hold tight for the update
