### ISSUE TITLE
Basic issues

### ISSUE THREAD

**Issue by AlexKLMan** [Julius-Bendt/homebridge-sonos-player#9]
Hi, I'm new to this plugin, and a little confuse.
First, how do I play an MP3 on my local Pi?
I know it's in the Track uri field but what do I enter, a path, I don't think Sonos have access to my Pi4.
I tried using a Dropbox url, but that doesn't work and HomeBridge just crashes.
Finally how do I use the TTS feature? I don't see that field.
Sorry if these questions are trivial but I am not finding anything in the read me.
Thank you.

**Comment by Julius-Bendt** [comment]
Hi Alex,

For serving mp3 files directly from the pi, I setup a nginx that serves as a proxy to the file system. 
I'll attach the configuration some time later for you. Keep in mind that this will only be fetchable from you LAN, unless you have a static ip - but you dont need this for the sonos player to play it. 

I haven't implemented TTS, as I figured I would just create a mp3 file if I ever needed it, and play it that way. For the same reason, I don't plan to implement this

**Comment by Julius-Bendt** [comment]
This is the nginx config I use:

```conf
# For hosting audio files
server {
    listen 1234; # Use any port 
    server_name localhost;

    location / {
        root /path/to/audio/files; # Change this root to where ever your audio files are
        index index.html;
    }
}
```
this lets you map files from the pi, to `http://192.168.1.2/file/path/filename.mp3`


If you want a custom (home) domain:
( Also include the above code block)
```conf
server {
    server_name audio.home;

    # Set headers
    proxy_set_header Host              $http_host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # set timeout
    proxy_read_timeout 60s;
    proxy_send_timeout 60s;
    send_timeout       60s;

    location / {
        proxy_pass http://192.168.1.2:1234/; #Use any port
    }
}
```
this lets you map files from the pi, to `http://audio.home/file/path/filename.mp3`
